-- Crear Base de Datos

create database dbp_bot_tuya;

-- alter table xxxxxx AUTO_INCREMENT=0;

use dbp_bot_tuya;

-- Tabla Administracion de Usuarios
create table tbl_rusuarios(
  PKUSU_NCODIGO int not null auto_increment primary key,    
  USU_CDOCUMENTO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CNOMBRES_APELLIDOS varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CUSUARIO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CROL varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CCARGO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CRESPONSABLE_GESTION varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  USU_CFECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USU_CFECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USU_CESTADO varchar(255) DEFAULT NULL    
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


create table tbl_status(
  PKSTA_NCODIGO int not null auto_increment primary key,    
  STA_CNOMBRE_PROCESO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CUSUARIO_INFOBIP varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CNOMBRE_ARCHIVO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CNOMBRE_FLUJO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CARCHIVO_CARGADO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CCANTIDAD_REGISTROS varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CFECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  STA_CREQ_SEGUIMIENTO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CFECHA_SEGUIMIENTO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CARCHIVO_RESULTANTE varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CPATH_RESULTANTE varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CFECHA_MODIFICACION TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  STA_CRESPONSABLE varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CCARGO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  STA_CESTADO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_rlog_detalle` (
  `PKLOG_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `LOG_ERROR_LOG` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `LOG_NAME_BOT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `LOG_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LOG_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_CDETALLE_REGISTRO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'Registro inicial Bot',
  `LOG_CESTADO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'InActivo',
  PRIMARY KEY (`PKLOG_NCODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tbl_rinfobip_users` (
  `PKINF_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `INF_CNOMBRE_USER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INF_CUSUARIO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INF_CCONTRASEÑA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INF_CRESPONSABLE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `INF_CCARGO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `INF_CFECHA_REGISTRO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `INF_CFECHA_MODIFICACION` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `INF_CESTADO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`PKINF_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb3 COLLATE=utf8_bin;

create table tbl_rflujos(
  PKFLU_NCODIGO int not null auto_increment primary key,    
  FKFLU_NINF_NCODIGO int not null,
  FLU_CNOMBRE_FLUJO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  FLU_CFECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  FLU_CFECHA_MODIFICACION TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FLU_CRESPONSABLE varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  FLU_CCARGO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  FLU_CESTADO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `tbl_rflujos` VALUES (1,4,'MORA MEDIA','2023-05-20 23:52:05','2023-05-21 04:40:57','ROGER.RODRIGUEZ','Administrador','InActivo'),(2,4,'MORA TEMPRANA','2023-05-20 23:52:05','2023-05-21 04:40:57','ROGER.RODRIGUEZ','Administrador','InActivo'),(3,5,'MORA MEDIA','2023-05-20 23:52:05','2023-05-21 04:40:57','ROGER.RODRIGUEZ','Administrador','Activo'),(4,5,'MORA TEMPRANA','2023-05-20 23:52:05','2023-05-21 04:40:57','ROGER.RODRIGUEZ','Administrador','Activo');

INSERT INTO `tbl_rinfobip_users` VALUES (1,'Gerencia','Gerencia_Medellin','Ger-med*2020','ROGER.RODRIGUEZ','Administrador','2023-05-20 18:19:15','2023-05-23 20:20:50','Inactivo'),(2,'Gerencia_02','Gerencia_Medellin_02','C0ntacto20**','ROGER.RODRIGUEZ','Administrador','2023-05-20 18:19:16','2023-05-23 20:20:50','Inactivo'),(3,'Gerencia_06','Gerencia_Medellin_06','Contacto@2019','ROGER.RODRIGUEZ','Administrador','2023-05-20 18:19:16','2023-05-23 20:20:50','Inactivo'),(4,'Gerencia_07','Gerencia_Medellin_07','C0ntacto@2020','ROGER.RODRIGUEZ','Administrador','2023-05-20 18:19:16','2023-05-23 20:20:50','Inactivo'),(5,'Gerencia_09','Gerencia_Medellin_09','Contacto@2019','ROGER.RODRIGUEZ','Administrador','2023-05-20 18:19:16','2023-05-20 18:19:16','Activo');
